version: '3.7'

services:
    api:
        image: 'node:13.0-alpine'
        container_name: api
        ports:
            - 127.0.0.1:3000:3000
        volumes:
            - './api:/home/node/app'
        working_dir: /home/node/app
        depends_on:
            - mongo
        links:
            - mongo
        command: ['sh', '-c', 'npm install && npm run start:dev']
        restart: always

    client:
        image: 'node:13.0-alpine'
        container_name: client
        ports:
            - 127.0.0.1:4200:4200
        volumes:
            - './client:/home/node/app'
        working_dir: /home/node/app
        command: ['sh', '-c', 'npm install && npm run start']
        restart: always

    mongo:
        image: 'mongo'
        container_name: mongo
        environment: 
            - MONGO_DATABASE = test
        ports:
            - 0.0.0.0:27017:27017